name: Build and deploy fullstack Node.js app to Azure Web App - e4square

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install and build client
      - name: Install and build frontend
        run: |
          cd client
          npm install
          CI='' npm run build
          cd ..

      # Install backend dependencies
      - name: Install backend
        run: |
          cd server
          npm install
          cd ..

      # 🪄 Flatten into deploy folder
      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp -r server/* deploy/
          cp -r client/build deploy/client/build
          cp server/package.json deploy/
          cp server/package-lock.json deploy/ || true  # ignore if doesn't exist

      - name: Zip deploy folder
        run: cd deploy && zip -r ../release.zip . && cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_13C4F3731C2D4E779398C9EE21954FB9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03BEF0893BDF4F26AEADE0769A1598F8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FA8FDBB738E6420381FF5E0B7E8C764D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'e4square'
          slot-name: 'Production'
          package: .
