name: Build and deploy Node.js app to Azure Web App - e4square

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 1: Install client dependencies
      - name: Install React client dependencies
        working-directory: ./client
        run: npm install

      # Step 2: Build React app with CI='' to avoid build failures on warnings
      - name: Build React app
        working-directory: ./client
        env:
          CI: ''
          NODE_ENV: production
        run: npm run build

      # Step 3: Move React build output to root-level client-build folder
      - name: Move frontend build to root/client-build
        run: |
          rm -rf client-build
          cp -r client/build ./client-build

      # Step 4: Move server.js and package.json to root
      - name: Move backend files to root
        run: |
          cp server/server.js .
          cp server/package.json .
          cp server/package-lock.json . || echo "No lock file found"

      # Step 5: Install backend dependencies
      - name: Clean and install backend dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      # Step 6: Zip artifact for deployment (excluding source dirs)
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r -x "client/*" "server/*" ".github/*" "node_modules/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_13C4F3731C2D4E779398C9EE21954FB9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03BEF0893BDF4F26AEADE0769A1598F8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FA8FDBB738E6420381FF5E0B7E8C764D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'e4square'
          slot-name: 'Production'
          package: .
